# Generated by Django 4.1.2 on 2022-12-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.courses', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.CharField(max_length=25, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lname',
            field=models.CharField(max_length=25, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='Username'),
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
